
rgbd_obstacle_layer:
  enabled:               true
  voxel_decay:           20 #seconds
  voxel_decay_static:    1.
  voxel_size:            0.05
  track_unknown_space:   true
  observation_persistence: 0.0
  max_obstacle_height:   2.0
  unknown_threshold:     15
  mark_threshold:        0
  combination_method:    1
  obstacle_range:        3.0
  origin_z:              0.0
  publish_voxel_map:     true
  observation_sources: rgbd1_clear rgbd1_mark
  rgbd1_mark:
    data_type: PointCloud2
    topic: camera1/depth/points
    marking: true
    clearing: false
    min_obstacle_height: 0.3
    max_obstacle_height: 2.0
  rgbd1_clear:
    data_type: PointCloud2
    topic: camera1/depth/points
    marking: false
    clearing: true
    min_z: 0.1
    max_z: 7.0
    vertical_fov_angle: 0.7
    horizontal_fov_angle: 1.04
